### ISSUE TITLE
sk参数的算法似乎不对。

### ISSUE THREAD

**Issue by satifanie** [asdanny/DD#5]
实际抓包中SK的值，跟计算的不一致。
似乎是 o p q r s 调换下顺序，但是对于不同的@t, 又不一样。目前还没有发现规律。

如果仅仅是用 PC 浏览器，完全模拟请求过程，结果又是跟实际算法一样的。

只是用anroid实际操作的不一样。

版本：v10.0.6

**Comment by asdanny** [comment]
高版本的不清楚，9.2.0版本的京东app刚测试过，没有问题。

**Comment by satifanie** [comment]
请问下，哪里有商品可以测试？我找了一圈也没有，想来验证一下。

你的算法跟tr.js里面的是一致的。
我碰到的问题主要是：我用抓包抓到https://tak.jd.com/t/41CD2的结果，通过sk_demo计算，
结果同submitOrder的手动点击提交的值不一致。 

不知道我描述的是否清楚。

**Comment by devcxm** [comment]
@asdanny  @satifanie 不能通过执行tr.js方法来加密吗？感觉这样比较靠谱。
